Update docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -24,10 +24,10 @@ jobs:
 
       - name: Build JAR
         run: |
-          ./mvnw clean package || { echo 'Maven build failed'; exit 1; }
+          ./mvnw clean package -e || { echo 'Maven build failed'; exit 1; }
 
-      - name: List target directory
-        run: ls -al target/ || echo 'Target directory does not exist'
+      - name: List Surefire reports
+        run: ls -al target/surefire-reports/
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
