Update docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -11,22 +11,23 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3  # Usando la versión más reciente
+        uses: actions/checkout@v3
 
       - name: Set execute permission for mvnw
-        run: chmod +x ./mvnw  # Establecer permisos de ejecución
+        run: chmod +x ./mvnw
 
       - name: Set up JDK 17
-        uses: actions/setup-java@v3  # Usando la versión más reciente
+        uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
 
       - name: Build JAR
-        run: ./mvnw clean package  # Asegúrate de que mvnw sea ejecutable
+        run: |
+          ./mvnw clean package || { echo 'Maven build failed'; exit 1; }
 
       - name: List target directory
-        run: ls -al target/
+        run: ls -al target/ || echo 'Target directory does not exist'
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
@@ -36,7 +37,7 @@ jobs:
 
       - name: Build Docker image
         run: |
-          IMAGE_TAG=${{ github.sha }}  # Usando el hash del commit como tag
+          IMAGE_TAG=${{ github.sha }}
           docker build . -t frankgallosanchez23/traductor_actions:${IMAGE_TAG} --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --build-arg DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
 
       - name: Push Docker image
